name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev pkg-config gcc-avr avr-libc avrdude

      - name: Install nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src

      # ---- Embedded crate ----

      - name: Build debouncer_rust (AVR)
        run: |
          cargo build \
            -p debouncer_rust \
            --target debouncer_rust/targets/avr-atmega328p.json \
            -Z build-std=core \
            -Z build-std-features=panic_immediate_abort

      # ---- Desktop crate ----
      - name: Build voltage_graph
        run: cargo build -p voltage_graph --verbose

      - name: Test voltage_graph
        run: cargo test -p voltage_graph --verbose
